config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users
  resources :sinsis do
    resources :likes, only: [:create, :destroy]
  end
  resources :comments

  get 'new', to: 'sinsis#new'
  get 'desc', to: 'sinsis#desc'
  get 'search', to: 'sinsis#search'
  get 'shuffle', to: 'sinsis#shuffle'
  get 'mypage', to: 'sinsis#mypage'

  get 'about', to: 'sinsis#about'
  get 'contact', to: 'sinsis#contact'

  root 'sinsis#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, length: { maximum: 50, message: "は50文字以内に抑えてください" }
  validates :body, presence: true
  belongs_to :user
  belongs_to :sinsi

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :sinsi, counter_cache: :likes_count
  belongs_to :user
end

app/models/sinsi.rb
class Sinsi < ApplicationRecord
  is_impressionable # preview
  mount_uploader :picture, PictureUploader # upload
  validates :title, length: { maximum: 30, message: "は30文字以内に抑えてください" }
  validates :word, length: { maximum: 50, message: "は50文字以内に抑えてください" }
  validates :picture, presence: true
  validate :picture_size

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def picture_size
    if picture.size > 3.megabytes
      errors.add(:picture, "のサイズは3MBまでにしてください")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 10, message: "は10文字以内に抑えてください" }
  validates :name, uniqueness: true

  has_many :sinsis, dependent: :destroy
  has_many :comments

  def sinsis
    return Sinsi.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception # CSRF
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # strong params
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]
  before_action :authenticate_user!, only: [:create]
  before_action :ensure_correct_comment_user, only: [:destroy]

  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to sinsi_path(@comment.sinsi_id), notice: 'コメントを書き込みました！' }
        format.json { render :show, status: :created, location: @sinsi }
      else
        format.html { redirect_to sinsi_path(@comment.sinsi_id), alert: 'コメントの書き込みに失敗しました' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to sinsi_path(@comment.sinsi_id), notice: 'コメントを削除しました！' }
      format.json { head :no_content }
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :sinsi_id, :user_id)
    end

    def ensure_correct_comment_user
      @comment = Comment.find_by(id: params[:id])
      if @comment.user_id != current_user.id
        flash[:alert] = "投稿者のみが削除できます"
        redirect_back(fallback_location: root_path)
      end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, sinsi_id: params[:sinsi_id])
    @likes = Like.where(sinsi_id: params[:sinsi_id])
    @sinsis = Sinsi.all
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, sinsi_id: params[:sinsi_id])
    like.destroy
    @likes = Like.where(sinsi_id: params[:sinsi_id])
    @sinsis = Sinsi.all
  end
end

app/controllers/sinsis_controller.rb
class SinsisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :mypage, :create, :update, :destroy]
  before_action :set_sinsi, only: [:edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  impressionist unique: [:user_id]

  def index
    @sinsis = Sinsi.all.order(id: "desc")
  end

  def search
    @search = 0
    @s        = Sinsi.search(params[:q])
    @sinsis = @s.result(distinct: true)
    render 'index'
  end

  def desc
    @sinsis = Sinsi.all
    render 'index'
  end

  def shuffle
    @sinsis = Sinsi.all.shuffle
    render 'index'
  end

  def show
    @sinsi = Sinsi.find_by(id: params[:id])
    @comment = @sinsi.comments.build
    @comments = @sinsi.comments.all
    @preview = Sinsi.find(params[:id])
    impressionist(@preview, nil, unique: [:user_id])
  end

  def new
    @sinsi = Sinsi.new
  end

  def edit
  end

  def mypage
    @sinsis = current_user.sinsis.all.length
    @comments = current_user.comments.all.length
    @sinsi = current_user.sinsis.build
    @sinsi_history = current_user.sinsis.all.order(id: "desc")
    @comment = current_user.comments.build
    @comment_history = current_user.comments.all.order(id: "desc")
  end

  def about
  end

  def contact
  end

  def create
    @sinsi = Sinsi.new(sinsi_params)

    respond_to do |format|
      if @sinsi.save
        format.html { redirect_to @sinsi, notice: '挿入が完了しました！' }
        format.json { render :show, status: :created, location: @sinsi }
      else
        format.html { render :new }
        format.json { render json: @sinsi.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sinsi.update(sinsi_params)
        format.html { redirect_to @sinsi, notice: '更新が完了しました！' }
        format.json { render :show, status: :ok, location: @sinsi }
      else
        format.html { render :edit }
        format.json { render json: @sinsi.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sinsi.destroy
    respond_to do |format|
      format.html { redirect_to sinsis_url, notice: '削除が完了しました！' }
      format.json { head :no_content }
    end
  end

  private

    def set_sinsi
      @sinsi = Sinsi.find(params[:id])
    end

    def sinsi_params
      params.require(:sinsi).permit(:title, :word, :picture, :user_id)
    end

    def ensure_correct_user
      @sinsi = Sinsi.find_by(id: params[:id])
      if @sinsi.user_id != current_user.id
        flash[:alert] = "挿入者のみが編集できます"
        redirect_back(fallback_location: root_path)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Sinsi Telegram"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def comment_user_name
    return User.find(@comment.user_id).name
  end
end

app/helpers/sinsis_helper.rb
module SinsisHelper

  def user_name
    return User.find(@sinsi.user_id).name
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if user_signed_in? %>
      <% omikuji = %W(大吉 吉 中吉 小吉 半吉 末吉 末小吉 平 凶 小凶 半凶 末凶 大凶).shuffle %>
      <!-- <%= "ID#{current_user.id}番の#{current_user.name}さんの今の運勢は、#{omikuji[0]}です！" %> -->
    <% end %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/Zbootstrap-theme.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Header -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Logo -->
          <%= link_to image_tag('logo.png', size: '40x40', id: 'sakura'), root_path %>
          <%= link_to 'Sinsi Telegram', root_path, class: 'navbar-brand' %>
        </div>

        <!-- User -->
        <div class="collapse navbar-collapse">
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              <%= link_to current_user.email, edit_user_registration_path, class: 'navbar-link' %> |
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
              <%= link_to "Log in", new_user_session_path, class: 'navbar-link'  %>
            <% end %>
          </p><br />

          <!-- Menu -->
          <ul class="nav navbar-nav">
            <li ><%= link_to 'desc', desc_path %></li>
            <li ><%= link_to 'search', search_path %></li>
            <li ><%= link_to 'Shuffle', shuffle_path %></li>
            <li ><%= link_to 'Insert', new_sinsi_path if user_signed_in? %></li>
            <li ><%= link_to 'Mypage', mypage_path if user_signed_in? %></li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Body -->
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% elsif alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <!-- Commmon -->
      <%= yield %>
    </div>

    <!-- Footer -->
    <footer>
      <div class="container">
        &copy; slicla 2019 - <%= link_to 'About', about_path %> - <%= link_to 'Contact', contact_path %>
      </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { sinsis: @sinsis, likes: @likes, like: @like}) %>")

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { sinsis: @sinsis, likes: @likes }) %>");

app/views/sinsis/_form.html.erb
<%= form_with(model: sinsi, local: true) do |form| %>
  <% if sinsi.errors.any? %>
    <div id="error_explanation">
      <div class="alert-danger">
        <ul class="validate">
          <% sinsi.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <br />
  <div class="field">
    <%= form.label "タイトル" %><em> (省略可)</em><br />
    <%= form.text_field :title, value: @sinsi.title, :placeholder => "無題" %>
  </div><br />

  <div class="field">
    <%= form.label "ひとこと" %><em> (省略可)</em><br />
    <%= form.text_field :word, value: @sinsi.word, :placeholder => "無言" %>
  </div><br />

  <div class="field">
    <%= form.label "投稿する画像の選択" %><br />
    <%= form.file_field :picture %>
  </div><br />

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit data: { confirm: '確定します。よろしいですか？' } %>
  </div>
<% end %>

app/views/sinsis/_like.html.erb
<% if user_signed_in? %>
  <% if sinsi.like_user(current_user.id) %>
    <%= button_to sinsi_like_path(like, sinsi_id: sinsi.id), method: :delete, id: "like-button", remote: true do %>
      <%= image_tag("icon_red_heart.png") %>
      <span>
        <%= sinsi.likes_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to sinsi_likes_path(sinsi), id: "like-button", remote: true do %>
      <%= image_tag("icon_heart.png") %>
      <span>
        <%= sinsi.likes_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <%= image_tag("icon_heart.png") %>
    <span>
      <%= sinsi.likes_count %>
    </span>
<% end %>

app/views/sinsis/about.html.erb
<% provide(:title, "About") %>

<h2>このサイトについて</h2>
<br />
<h4> Q. Sinsiって何の略ですか？</h4><br />
<p>Ａ. よくわかんない</p>
<!-- Sinsi Is Not Sakura Insta! -->

app/views/sinsis/contact.html.erb
<% provide(:title, "Contact") %>

<h2>お問い合わせ</h2>
<br />
<h4> お問い合わせの前にこちらもご覧ください</h4><br />
<p><b><%= link_to 'Google', 'https://www.google.co.jp'%></b></p>

app/views/sinsis/edit.html.erb
<% provide(:title, "Update") %>

<h2>手軽にアップデートしよう！</h2>

<%= render 'form', sinsi: @sinsi %>

<br />
<%= button_to '削除する', sinsi_path(@sinsi.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
<br />
<%= link_to '戻る', @sinsi %>

app/views/sinsis/index.html.erb
<% provide(:title, "Home") %>

<h2>投稿画像一覧</h2>
<% unless @search.nil? %>
<%= search_form_for @s do |f| %>
  <%= f.label :title_or_word_cont, "キーワード検索(タイトル&ひとこと)" %>
  <%= f.search_field :title_or_word_cont %>
  <%= f.submit %>
<% end %>
<% end %>

<% @sinsis.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |sinsi| %>
      <div class="col-md-4">
        <p class="post"><b>投稿日: </b><%= sinsi.created_at.to_s.chop.chop.chop.chop.chop.chop.chop.chop.chop %></p>
        <%= link_to image_tag(sinsi.picture_url(:thumb)), sinsi, id: 'thumbnail' if sinsi.picture.present? %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/sinsis/mypage.html.erb
<% provide(:title, "#{current_user.name}'s page") %>

<h2><%= "#{current_user.name}さんのステータス" %></h2>
<br />

<h3>コメント履歴 ( 計 <%= "#{@comments} 回 )" %></h3>
<% @comment_history.each do |comment| %>
  <div id="bbs">
    <p><%= comment.body %></p>
      <%= link_to "削除する", comment_path(comment.id), method: :delete, data: { confirm: "削除しますか？"} %>
    </div>
  <% end %>

<h3>インサート一覧 ( 計 <%= "#{@sinsis} 回 )" %></h3>
<% @sinsi_history.in_groups_of(5) do |group| %>
  <div class="srow">
    <% group.compact.each do |sinsi| %>
      <div class="col-md-4">
        <p id="post"><%= link_to '編集する', edit_sinsi_path(sinsi) %></p>
        <%= link_to image_tag(sinsi.picture_url(:icon)), sinsi, id: 'icon' if sinsi.picture.present? %>
      </div>
    <% end %>
  </div>
<% end %>

 <%
=begin%>
 被コメント 計 (未実装) 回
いいね！ 計 (未実装) 回
被 いいね！ 計 (未実装) 回
<%
=end%>

app/views/sinsis/new.html.erb
<% provide(:title, "Insert") %>

<h2>手軽にインサートしよう！</h2>

<%= render 'form', sinsi: @sinsi %>

app/views/sinsis/show.html.erb
<% if @sinsi.title.blank? %>
  <% provide(:title, "無題") %>
<% else %>
  <% provide(:title, "#{@sinsi.title}") %>
<% end %>

<% if @sinsi.title.blank? %>
  <h2>無題
<% else %>
  <h2><%= @sinsi.title %>
<% end %>

<% if user_signed_in? %>
  <% if @sinsi.user_id == current_user.id %>
    <span style="font-size: 13px"><%= link_to '編集する', edit_sinsi_path(@sinsi) %><br />
  <% end %>
<% end %></h2><br />

<%
=begin%>
 <%= render 'like', sinsi: @sinsi_id %>
<%
=end%>
<p><b>投稿ユーザー名: </b><%= "#{user_name}" %> さん</p>
<p><b>閲覧ユーザー数: </b><%= @preview.impressionist_count %> 人</p>
<p><b>最終更新日: </b><%= @sinsi.updated_at.to_s.chop.chop.chop.chop.chop.chop.chop.chop.chop %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@sinsi.picture_url, width: '100%') if @sinsi.picture.present? %>
    <% if @sinsi.word.blank? %>
      <h3><b>「 </b>無言<b> 」</b></h3>
    <% else %>
      <h3><b>「 </b><%= @sinsi.word %><b> 」</b></h3>
    <% end %><br />

    <h4>コメント一覧</h4>
    <%= '<div id="bbs"><h4>最初のコメントを投稿しませんか？</h4></div>'.html_safe if @comments.empty? %>
    <br />
    <% i = 0 %>
    <% @comments.each do |comment| %>
      <div id="bbs">
        <p><%= "#{i+=1} " %>
        <span style="color: green;"><%= comment.user.name %>さん</span><%= " (投稿者)" if comment.user.name == user_name %><%= " #{comment.created_at.to_s.chop.chop.chop.chop.chop}" %></p>
        <p><%= comment.body %></p>
        <% if user_signed_in? %>
          <% if comment.user.name == current_user.name %>
            <%= link_to "削除する", comment_path(comment.id), method: :delete, data: { confirm: "削除しますか？"} %>
          <% end %>
        <% end %>
        </div>
      <% end %>
    <br />

    <%= form_for(@comment, local: true) do |form| %>
      <div class="field">
        <%= form.text_area :body, size: "50x3", placeholder: 'コメント内容(50文字以内)', maxlength: '50' %>
      </div><br />

      <%= form.hidden_field :sinsi_id, value: @sinsi.id %>
      <%= form.hidden_field :user_id, value: current_user.id if user_signed_in? %>

      <%= form.submit 'コメントする', data: { confirm: '確定します。よろしいですか？' } %>
    <% end %>

    <br />
    <p><%= link_to '戻る', sinsis_path %></p>
  </div>
</div>